In [9]:
import torch
import torchvision
import torchvision.transforms as transforms
import torchvision.models as models
import torch.optim as optim
import torch.nn as nn
import torchmetrics
import random
import numpy as np
import matplotlib.pyplot as plt
from math import ceil

### Matrix convolution implementation

In [23]:
def matrix_convolve(input: np.ndarray, kernel: np.ndarray, stride: int = 1) -> np.ndarray:
    """Performs basic convolution on 2d input with 2d kernel.

    Parameters
    ----------
    input : np.ndarray
        The input matrix on which convolution is performed
    kernel : np.ndarray
        The convolution kernel (also matrix)
    stride : np.ndarray, optional
        The amount of pixels that kernel moves on each iteration (if the next stride would move kernel outside of possible area kernel moves down and start again from the left or stops if it's impossible to move down)

    Returns
    -------
    np.ndarray
        A result of convolution
    """
    
    # Check for correct input data
    if len(input.shape) != 2: raise Exception("Error: input should be a 2d matrix")
    if len(kernel.shape) != 2: raise Exception("Error: kernel should be a 2d matrix")
    if np.any(kernel.shape > input.shape): raise Exception("Error: kernel can't be bigger than input in any dimension")
    if stride < 1: raise Exception("Error: stride should be an integer greater than or equal 1")

    # Get dimensions of input and kernel, as well as amount of steps needed
    input_h, input_w = input.shape
    kernel_h, kernel_w = kernel.shape
    delta_h = ceil((input_h - kernel_h + 1) / stride)
    delta_w = ceil((input_w - kernel_w + 1) / stride)
    # Define convolution result matrix
    conv_res = np.zeros((delta_h, delta_w ))
    
    # Perform convolution, first cycle controls vertical kernel movement,
    # second - horizontal movement
    for i in range(delta_h):
        for j in range(delta_w):
            conv_res[i, j] = np.sum(input[i * stride:i * stride + kernel_h, j * stride:j * stride + kernel_w] * kernel)
            
    return conv_res

# Test 1
input = np.arange(16).reshape((4, 4))
kernel = np.ones((2, 2)) / 4
print(matrix_convolve(input, kernel))

# Test 2
input2 = np.arange(25).reshape((5, 5))
print(matrix_convolve(input2, kernel, stride = 2))

[[ 2.5  3.5  4.5]
 [ 6.5  7.5  8.5]
 [10.5 11.5 12.5]]
[[ 3.  5.]
 [13. 15.]]
